import type { Metadata } from "next";
import InnerPages from "../../components/InnerPages";
import ServiceDetailExperience, { type ServiceDetail } from "../../components/ServiceDetailExperience";
import { getPortfolioProjects } from "../../../lib/content-store";
export const dynamic = "force-dynamic";
export const runtime = "nodejs";
export const metadata: Metadata={title:"Web Design in St. Catharines & Niagara | Assist My Day",description:"Custom web design and e-commerce development for businesses in St. Catharines and Niagara. Explore our work and discuss your website with Assist My Day.",alternates:{canonical:"https://assistmyday.com/services/websites-ecommerce"}};
const detail:ServiceDetail={number:"02",title:"Websites & E-commerce",chapterMarker:"02 / WHY WEB",kicker:"EXPERIENCES THAT CONVERT",hero:["Web Design & Development", "in St. Catharines and Niagara"],intro:"Assist My Day builds business websites, e-commerce stores and landing pages for companies in St. Catharines and across Niagara. Whether you need a new website or a redesign, we focus on clear navigation, mobile usability and making it easy for customers to enquire or buy.",nodes:["UX","SEO","CMS","COMMERCE"],marquee:["STRATEGY","UX / UI","DEVELOPMENT","ECOMMERCE","OPTIMIZATION"],fitTitle:["When your website must","do more than look good."],fitCopy:"Your website should clarify your value, remove friction, and guide every visitor toward a meaningful next step. We connect strategy, design, engineering, content, and measurement in one accountable team.",outcomes:[["SPEED","Create faster experiences","<2s"],["CONVERSION","Turn visits into action","CRO"],["CONTROL","Make content easy to manage","24/7"]],sectionLabel:"WHAT WE CREATE",sectionTitle:["Every touchpoint.","Built to perform."],capabilities:[["01","Corporate websites","Credible, flexible digital platforms that communicate complex offers with clarity."],["02","E-commerce stores","Frictionless product discovery, checkout, payment, and retention experiences."],["03","Landing pages","Focused campaign destinations engineered around one measurable action."],["04","CMS platforms","Simple publishing systems that give your team control without compromising quality."]],processIntro:"Strategy, content, UX, development, launch, and optimization stay connected from the first workshop to every release.",process:[["01","Discover","Define audiences, objectives, journeys, content, and measures."],["02","Prototype","Shape the information architecture and validate key interactions."],["03","Build","Develop responsively with performance, accessibility, and SEO built in."],["04","Optimize","Launch, measure behavior, and improve conversion over time."]],stackLabel:"PLATFORMS",stackTitle:["Flexible technology.","Frictionless management."],stack:["Next.js","WordPress","Shopify","WooCommerce","Webflow","Stripe","GA4 & GTM","Cloudflare"],contactKicker:"START A WEB PROJECT",contactTitle:["Build an experience","people act on."],contactCopy:"Tell us what your website or store needs to achieve. We’ll respond with a focused path from idea to launch."};
export default async function Page() {
  const projects = (await getPortfolioProjects()).filter(project => project.published && /website|web design|e-commerce/i.test(project.category)).slice(0, 3);
  return <InnerPages active="SERVICES"><ServiceDetailExperience detail={detail} projects={projects}/></InnerPages>;
}
