import type { PortfolioProject, ServiceItem } from "./content-types";

export const portfolioSeeds: PortfolioProject[] = [
  { title: "Signarama Brampton", slug: "signarama-brampton", category: "Website / Lead generation / Social Media Management / SEO", image: "/portfolio-signarama-home.webp", projectUrl: "https://signarama-bramptonwest.ca/", description: "Problem: local signage buyers needed a clearer path from search to the right service. Work: service architecture, location-led content, responsive design, SEO foundations, and enquiry journeys. Outcome: a live mobile-ready site that guides visitors from service discovery to a quote request.", size: "large", side: "left", sortOrder: 1, published: true },
  { title: "Signarama Toronto", slug: "signarama-toronto", category: "Website / Lead generation / Social Media Management / SEO", image: "/portfolio-signarama-about.webp", projectUrl: "https://signarama-toronto.ca/", description: "Problem: a broad signage offer was difficult to scan and compare online. Work: reorganized services, clarified page hierarchy, improved mobile presentation, and established search-ready content patterns. Outcome: a live website where buyers can identify the relevant signage solution and reach the team quickly.", size: "medium", side: "right", sortOrder: 2, published: true },
  { title: "Rio Immigration", slug: "rio-immigration", category: "Website / Lead generation / Social Media Management / SEO / CRM Tool", image: "/portfolio-rio-immigration.webp", projectUrl: "https://rioimm.ca/", description: "Problem: prospective clients needed to understand complex immigration pathways without added confusion. Work: structured the service content, designed trust-focused journeys, connected lead capture, and supported CRM-ready follow-up. Outcome: a live platform that makes services easier to evaluate and gives visitors a direct consultation path.", size: "large", side: "left", sortOrder: 3, published: true },
  { title: "Consortium Staffing", slug: "consortium-staffing", category: "Website / Social Media Management / SEO", image: "/portfolio-consortium-staffing.webp", projectUrl: "https://consortiumstaffing.ca/", description: "Problem: employers and candidates entered the staffing journey with different needs. Work: separated those journeys, clarified recruitment services, modernized the responsive experience, and strengthened search foundations. Outcome: a live recruitment site that routes each audience toward the right next step.", size: "xlarge", side: "center", sortOrder: 4, published: true },
  { title: "The Burke Group", slug: "the-burke-group", category: "Website", image: "/portfolio-burke-group.webp", projectUrl: "https://theburkegroup.com/", description: "Problem: an executive-search firm needed its digital presence to reflect the discretion and authority of its work. Work: refined information hierarchy, responsive presentation, and consultation pathways. Outcome: a live corporate site that explains the firm's expertise and supports high-value enquiries.", size: "large", side: "right", sortOrder: 5, published: true },
  { title: "AMD Studios", slug: "amd-studios", category: "Website / Lead generation / Social Media Management / SEO", image: "/portfolio-amd-studios.webp", projectUrl: "https://amdstudios.ca/", description: "Problem: a visual studio needed to show the quality of its work without making booking difficult. Work: image-led page design, simplified service discovery, responsive layouts, and clearer enquiry paths. Outcome: a live portfolio and booking experience that keeps the work central while making the next step obvious.", size: "medium", side: "left", sortOrder: 6, published: true },
  { title: "GeoSolar", slug: "geosolar", category: "Website / Social Media Management / SEO", image: "/portfolio-geosolar.webp", projectUrl: "https://geosolarheater.com/", description: "Problem: technical heating products needed a simpler homeowner explanation. Work: translated product details into benefit-led content, created responsive product journeys, and added search-ready structure. Outcome: a live educational site that helps visitors understand the technology and request more information.", size: "large", side: "right", sortOrder: 7, published: true },
  { title: "Vishal Bangarh", slug: "vishal-bangarh", category: "Website / Social Media Management / SEO", image: "/portfolio-vishal-bangarh.webp", projectUrl: "https://vishalbangarh.com/", description: "Problem: a local real-estate professional needed a distinct platform beyond listing portals. Work: personal-brand presentation, neighbourhood-focused content, responsive design, SEO foundations, and evaluation lead capture. Outcome: a live owned channel that connects local expertise with home-evaluation enquiries.", size: "xlarge", side: "center", sortOrder: 8, published: true },
];

export const serviceSeeds: ServiceItem[] = [
  { number: "01", title: "Custom Software Development", label: "SYSTEMS THAT SCALE", copy: "Purpose-built platforms, portals, dashboards, and automations designed around the way your organization actually works.", items: ["Web applications", "Business portals", "API integrations", "Workflow automation"], motif: "rings", sortOrder: 1, published: true },
  { number: "02", title: "Websites & E-commerce", label: "EXPERIENCES THAT CONVERT", copy: "Fast, accessible, conversion-focused websites and commerce journeys that communicate clearly and create measurable action.", items: ["UX strategy", "Web design", "Development", "E-commerce"], motif: "frame", sortOrder: 2, published: true },
  { number: "03", title: "Performance Marketing", label: "GROWTH YOU CAN MEASURE", copy: "Connected search, paid media, content, CRO, and analytics programs that turn attention into qualified demand.", items: ["SEO", "Paid media", "Content", "Analytics & CRO"], motif: "signal", sortOrder: 3, published: true },
  { number: "04", title: "Brand, Content & Social", label: "RECOGNITION THAT LASTS", copy: "Distinctive identities and channel-ready creative systems that build recognition, trust, and long-term audience engagement.", items: ["Brand strategy", "Visual identity", "Campaigns", "Social content"], motif: "orbit", sortOrder: 4, published: true },
];
