import type { PortfolioProject, ServiceItem } from "./content-types";

export const portfolioSeeds: PortfolioProject[] = [
  { title: "Signarama Brampton", slug: "signarama-brampton", category: "Website / Lead generation", image: "/portfolio-signarama-home.webp", projectUrl: "/contact", description: "A conversion-focused storefront signage website built to turn local search demand into qualified enquiries.", size: "large", side: "left", sortOrder: 1, published: true },
  { title: "Signarama Toronto", slug: "signarama-toronto", category: "SEO / Content experience", image: "/portfolio-signarama-about.webp", projectUrl: "/contact", description: "A clear, search-ready content experience for one of Toronto's established sign companies.", size: "medium", side: "right", sortOrder: 2, published: true },
  { title: "Rio Immigration", slug: "rio-immigration", category: "Web platform / Strategy", image: "/portfolio-rio-immigration.webp", projectUrl: "/contact", description: "A trust-led immigration platform that simplifies complex services and guides visitors toward consultation.", size: "large", side: "left", sortOrder: 3, published: true },
  { title: "Consortium Staffing", slug: "consortium-staffing", category: "Recruitment / Digital product", image: "/portfolio-consortium-staffing.webp", projectUrl: "/contact", description: "A modern recruitment experience connecting employers, candidates, and staffing expertise.", size: "xlarge", side: "center", sortOrder: 4, published: true },
  { title: "The Burke Group", slug: "the-burke-group", category: "Brand platform / Executive search", image: "/portfolio-burke-group.webp", projectUrl: "/contact", description: "A refined executive-search platform designed around authority, relationships, and high-value consultation.", size: "large", side: "right", sortOrder: 5, published: true },
  { title: "AMD Studios", slug: "amd-studios", category: "Website / Conversion design", image: "/portfolio-amd-studios.webp", projectUrl: "/contact", description: "An elegant studio website that turns visual storytelling into an intuitive booking journey.", size: "medium", side: "left", sortOrder: 6, published: true },
  { title: "GeoSolar", slug: "geosolar", category: "Marketing / Sustainability", image: "/portfolio-geosolar.webp", projectUrl: "/contact", description: "A performance-driven sustainability website translating technical products into clear homeowner value.", size: "large", side: "right", sortOrder: 7, published: true },
  { title: "Vishal Bangarh", slug: "vishal-bangarh", category: "Real estate / Lead generation", image: "/portfolio-vishal-bangarh.webp", projectUrl: "/contact", description: "A personal real-estate platform built to create local credibility and generate evaluation leads.", size: "xlarge", side: "center", sortOrder: 8, published: true },
];

export const serviceSeeds: ServiceItem[] = [
  { number: "01", title: "Custom Software Development", label: "SYSTEMS THAT SCALE", copy: "Purpose-built platforms, portals, dashboards, and automations designed around the way your organization actually works.", items: ["Web applications", "Business portals", "API integrations", "Workflow automation"], motif: "rings", sortOrder: 1, published: true },
  { number: "02", title: "Websites & E-commerce", label: "EXPERIENCES THAT CONVERT", copy: "Fast, accessible, conversion-focused websites and commerce journeys that communicate clearly and create measurable action.", items: ["UX strategy", "Web design", "Development", "E-commerce"], motif: "frame", sortOrder: 2, published: true },
  { number: "03", title: "Performance Marketing", label: "GROWTH YOU CAN MEASURE", copy: "Connected search, paid media, content, CRO, and analytics programs that turn attention into qualified demand.", items: ["SEO", "Paid media", "Content", "Analytics & CRO"], motif: "signal", sortOrder: 3, published: true },
  { number: "04", title: "Brand, Content & Social", label: "RECOGNITION THAT LASTS", copy: "Distinctive identities and channel-ready creative systems that build recognition, trust, and long-term audience engagement.", items: ["Brand strategy", "Visual identity", "Campaigns", "Social content"], motif: "orbit", sortOrder: 4, published: true },
];
